/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invocing

import spock.lang.Specification

class AppTest extends Specification {

    def "dummy main method test"() {
        setup:
        def app = new App()

        when:
        def result = app.main()

        then:
        result == null
    }
}
